### PR TITLE
unit tests

### PR DESCRIPTION
**Pull request by ngokevin**
Unit test recorders and players.

Actual code changes include:

- Fixes to event playing due to wrong variable names used.
- Handle `axismove` event, which has different event details than the buttons.
- Use `camera-set-active` (camera set) rather than `camera-ready` (camera created).

### CODE REVIEW

**Comment by dmarcos** [comment]
It's nice to have the infrastructure in place but I would not put too much effort now until the API consolidates a bit

**Comment by ngokevin** [comment]
Tests will let you progress the API without worry about breaking functionality.

**Comment by ngokevin** [comment]
Rebased.

**Comment by dmarcos** [comment]
Merging. but tests can slow you down without knowing what functionality you want yet. unit tests are better introduced when API starts to cristalize

**Pull request merged**
